// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/guil95/go-wire-di/internal/repository"
	"github.com/guil95/go-wire-di/internal/usecase"
	"github.com/guil95/go-wire-di/pkg/database"
)

// Injectors from wire.go:

func SetupApp() *App {
	db := database.NewMysqlDB()
	repositoryRepository := repository.NewMysqlRepository(db)
	useCase := usecase.NewUseCase(repositoryRepository)
	app := &App{
		uc: useCase,
	}
	return app
}
